apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-http
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-http
  template:
    metadata:
      labels:
        app: sample-http
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-http
  namespace: default
spec:
  selector:
    app: sample-http
  ports:
    - name: http
      port: 80
      targetPort: http
